// Auto-generated by fumadocs-mdx
// @ts-nocheck -- skip type checking
import { _runtimeAsync, buildConfig } from "fumadocs-mdx/runtime/async"
const _sourceConfig = buildConfig(_source)
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const meta = _runtime.meta<typeof _source.meta>([]);
export const stories = _runtimeAsync.doc<typeof _source.stories>([], "stories", _sourceConfig)
